ckdproject/ckdApp/urls.py
from django.conf.urls import url
from ckdApp import views
from django.urls import path

app_name = 'ckdApp'

urlpatterns = [
    path('', views.dataUploadView.as_view(), name = 'ckd'),
    #path('whats', views.WhatsappAnalaysis.as_view(), name = 'whats'),
    #path('result', views.finalresult.as_view(), name= 'result'),
    #path('success', views.Success.as_view(), name = 'success'),
    #path('fail',views.Failure.as_view(),name='fail'),
    #path('filenot',views.FileNotfound.as_view(), name='filenot'),
    #path('aboutus',views.AboutUs.as_view(), name='aboutus')
]

ckdproject/ckdApp/models.py
from django.db import models

# Create your models here.
class ckdModel(models.Model):

    Blood_Glucose_Random=models.FloatField()
    Blood_Urea=models.FloatField()
    Serum_Creatine=models.FloatField()
    Packed_cell_volume=models.FloatField()
    White_blood_count=models.FloatField()

ckdproject/ckdApp/forms.py
from django import forms
from .models import *


class ckdForm(forms.ModelForm):
    class Meta():
        model=ckdModel
        fields=['Blood_Glucose_Random','Blood_Urea','Serum_Creatine','Packed_cell_volume','White_blood_count']

ckdproject/ckdApp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect
#from .forms import *
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
ListView,DetailView,
CreateView,DeleteView,
UpdateView)
from . import models
from .forms import *
from django.core.files.storage import FileSystemStorage
#from topicApp.Topicfun import Topic
#from ckdApp.funckd import ckd
#from sklearn.tree import export_graphviz #plot tree
#from sklearn.metrics import roc_curve, auc #for model evaluation
#from sklearn.metrics import classification_report #for model evaluation
##from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(df2.drop('classification_yes', 1), df2['classification_yes'], test_size = .2, random_state=10)

import time
import pandas as pd
import numpy as np
#from sklearn.preprocessing import StandardScaler
#from sklearn.feature_selection import SelectKBest
#from sklearn.feature_selection import chi2
#from sklearn.model_selection import train_test_split
#from sklearn.decomposition import PCA
#from sklearn.feature_selection import RFE
#from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
#import eli5 #for purmutation importance
#from eli5.sklearn import PermutationImportance
#import shap #for SHAP values
#from pdpbox import pdp, info_plots #for partial plots
np.random.seed(123) #ensure reproduc
class dataUploadView(View):
    form_class = ckdForm
    success_url = reverse_lazy('success')
    template_name = 'create.html'
    failure_url= reverse_lazy('fail')
    filenot_url= reverse_lazy('filenot')
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    def post(self, request, *args, **kwargs):
        #print('inside post')
        form = self.form_class(request.POST, request.FILES)
        #print('inside form')
        if form.is_valid():
            form.save()
            data_bgr= request.POST.get('Blood_Glucose_Random')
            data_bu=request.POST.get('Blood_Urea')
            data_sc=request.POST.get('Serum_Creatine')
            data_pcv=request.POST.get('Packed_cell_volume')
            data_wc=request.POST.get('White_blood_count')
            #print (data)
            #dataset1=pd.read_csv("prep.csv",index_col=None)
            dicc={'yes':1,'no':0}
            filename = 'finalized_model_ckd.sav'
            classifier = pickle.load(open(filename, 'rb'))

            data = np.array([data_bgr,data_bu,data_sc,data_pcv,data_wc])
            #sc = StandardScaler()
            #data = sc.fit_transform(data.reshape(-1,1))
            out=classifier.predict(data.reshape(1,-1))
# providing an index
            #ser = pd.DataFrame(data, index =['bgr','bu','sc','pcv','wbc'])

            #ss=ser.T.squeeze()
#data_for_prediction = X_test1.iloc[0,:].astype(float)

#data_for_prediction =obj.pca(np.array(data_for_prediction),y_test)
            #obj=ckd()
            ##plt.savefig("static/force_plot.png",dpi=150, bbox_inches='tight')







            return render(request, "succ_msg.html", {'data_bgr':data_bgr,'data_bu':data_bu,'data_sc':data_sc,'data_pcv':data_pcv,'data_wc':data_wc,
                                                        'out':out})


        else:
            return redirect(self.failure_url)

ckdproject/ckdApp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
    body {
      background-image: url("{% static 'output_image/backgroud.PNG' %}");
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: 100% 100%;
          }
    .navbar-default {
    background-color: #075E54;
    border-color: #030033;
}

    </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-default navbar-dark">
  <!-- Brand -->
      <a class="navbar-brand" href="{% url 'ckdApp:ckd' %}">Home</a>

      <!-- Links -->
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'ckdApp:ckd' %}">CKD</a>
        </li>

      </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>
  </body>

</html>

ckdproject/ckdApp/templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="jumbotron">
  <h1>Chronic Kidney Disease</h1>
  <head>
    Please enter repective fields
  </head>

    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">upload</button>
    </form>
  </div>
{% endblock %}

ckdproject/ckdApp/templates/succ_msg.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}
<div class="jumbotron">
    <h1>Chronic Kidney Disease </h1>
    <div class="fieldWrapper">
      <h2>For the values</h2>
      <p>Blood_Glucose_Random:{{data_bgr}}</p>
      <p>Blood_Urea:{{data_bu}}</p>
      <p>Serum_Creatine:{{data_sc}}</p>
      <p>Packed_cell_volume:{{data_pcv}}</p>
      <p>White_blood_count:{{data_wc}}</p>
      <br>
      {% if out == 1 %}
        <p>You <b>will have</b>  chronic Kidney Disease in the future: <b>Positive</b></p>
      {% else %}
        <p>You <b>will not</b> have  chronic Kidney Disease in the future:<b>Negetive</b></p>

      {% endif %}
    
    <a  href="{% url 'ckdApp:ckd' %}">CKD Predicition</a>
    <br>
</div>
{% endblock %}